import type {
  Client,
  Project,
  Lead,
  RevenueDataPoint,
  ApprovalItem,
  Invoice,
  OpportunityAlert,
  AxisProject,
} from './types'

// TODO: replace with GET /api/clients
export const clients: Client[] = [
  {
    id: 'c1',
    name: 'Axis Mutual Fund',
    shortName: 'Axis MF',
    status: 'high-value',
    retainerValue: 850000,
    activeProjects: 4,
    outstandingInvoices: 2550000,
    accountManager: 'Priya Mehta',
    industry: 'Mutual Funds',
    lastActivity: '2026-06-19',
  },
  {
    id: 'c2',
    name: 'Motilal Oswal AMC',
    shortName: 'Motilal Oswal',
    status: 'active',
    retainerValue: 650000,
    activeProjects: 3,
    outstandingInvoices: 975000,
    accountManager: 'Rajan Kapoor',
    industry: 'Mutual Funds',
    lastActivity: '2026-06-20',
  },
  {
    id: 'c3',
    name: 'Kotak Mutual Fund',
    shortName: 'Kotak MF',
    status: 'at-risk',
    retainerValue: 500000,
    activeProjects: 2,
    outstandingInvoices: 1500000,
    accountManager: 'Sneha Dixit',
    industry: 'Mutual Funds',
    lastActivity: '2026-06-08',
  },
  {
    id: 'c4',
    name: 'DSP Mutual Fund',
    shortName: 'DSP MF',
    status: 'active',
    retainerValue: 420000,
    activeProjects: 2,
    outstandingInvoices: 630000,
    accountManager: 'Priya Mehta',
    industry: 'Mutual Funds',
    lastActivity: '2026-06-17',
  },
  {
    id: 'c5',
    name: 'Tata Mutual Fund',
    shortName: 'Tata MF',
    status: 'active',
    retainerValue: 380000,
    activeProjects: 2,
    outstandingInvoices: 380000,
    accountManager: 'Rajan Kapoor',
    industry: 'Mutual Funds',
    lastActivity: '2026-06-15',
  },
  {
    id: 'c6',
    name: 'Invesco Mutual Fund',
    shortName: 'Invesco MF',
    status: 'low-margin',
    retainerValue: 280000,
    activeProjects: 1,
    outstandingInvoices: 840000,
    accountManager: 'Sneha Dixit',
    industry: 'Mutual Funds',
    lastActivity: '2026-06-12',
  },
  {
    id: 'c7',
    name: 'HDFC AMC',
    shortName: 'HDFC AMC',
    status: 'high-value',
    retainerValue: 920000,
    activeProjects: 5,
    outstandingInvoices: 1380000,
    accountManager: 'Arjun Nair',
    industry: 'Mutual Funds',
    lastActivity: '2026-06-21',
  },
  {
    id: 'c8',
    name: 'Nippon India MF',
    shortName: 'Nippon MF',
    status: 'active',
    retainerValue: 340000,
    activeProjects: 2,
    outstandingInvoices: 510000,
    accountManager: 'Arjun Nair',
    industry: 'Mutual Funds',
    lastActivity: '2026-06-14',
  },
]

// TODO: replace with GET /api/projects
export const projects: Project[] = [
  {
    id: 'p1',
    clientId: 'c1',
    clientName: 'Axis MF',
    name: 'Retirement Planning — 10-Part Reel IP',
    status: 'on-track',
    budget: 450000,
    spent: 210000,
    dueDate: '2026-07-15',
    deliverableType: 'reels',
    workflowStage: 'script',
    description: '10-episode educational reel series on retirement corpus building for the 35–50 age segment',
  },
  {
    id: 'p2',
    clientId: 'c1',
    clientName: 'Axis MF',
    name: 'SIP Starts Early — Static Campaign (Q2)',
    status: 'awaiting-client',
    budget: 180000,
    spent: 162000,
    dueDate: '2026-06-28',
    deliverableType: 'statics',
    workflowStage: 'client-share',
    description: 'Series of 8 static posts for Instagram + LinkedIn promoting early SIP adoption',
  },
  {
    id: 'p3',
    clientId: 'c1',
    clientName: 'Axis MF',
    name: 'June Newsletter — Debt Fund Outlook',
    status: 'on-track',
    budget: 75000,
    spent: 45000,
    dueDate: '2026-06-25',
    deliverableType: 'newsletter',
    workflowStage: 'visual-treatment',
    description: 'Monthly investor newsletter with fund house commentary and category outlook',
  },
  {
    id: 'p4',
    clientId: 'c2',
    clientName: 'Motilal Oswal',
    name: 'MOSt Focused 25 — Brand Film',
    status: 'blocked',
    budget: 380000,
    spent: 95000,
    dueDate: '2026-07-01',
    deliverableType: 'video',
    workflowStage: 'compliance-review',
    description: 'Hero brand film for MOSt Focused 25 fund showcasing 15-year performance story',
  },
  {
    id: 'p5',
    clientId: 'c2',
    clientName: 'Motilal Oswal',
    name: 'Wealth Manager Education — Deck Series',
    status: 'on-track',
    budget: 220000,
    spent: 110000,
    dueDate: '2026-07-10',
    deliverableType: 'deck',
    workflowStage: 'script',
    description: '4-part pitch deck series for wealth manager education programs',
  },
  {
    id: 'p6',
    clientId: 'c3',
    clientName: 'Kotak MF',
    name: 'Kotak Flexi Cap — Awareness Reels',
    status: 'delayed',
    budget: 240000,
    spent: 144000,
    dueDate: '2026-06-20',
    deliverableType: 'reels',
    workflowStage: 'feedback',
    description: 'Series of 6 short-form reels demystifying flexi-cap as a category',
  },
  {
    id: 'p7',
    clientId: 'c4',
    clientName: 'DSP MF',
    name: 'Tiger Fund — 25 Year Milestone Campaign',
    status: 'on-track',
    budget: 320000,
    spent: 96000,
    dueDate: '2026-07-30',
    deliverableType: 'mixed',
    workflowStage: 'creative-territory',
    description: 'Full 360 campaign celebrating DSP Tiger Fund — 25th anniversary milestone',
  },
  {
    id: 'p8',
    clientId: 'c5',
    clientName: 'Tata MF',
    name: 'Mid Cap Opportunities — Advisor Deck',
    status: 'awaiting-review',
    budget: 95000,
    spent: 85500,
    dueDate: '2026-06-22',
    deliverableType: 'deck',
    workflowStage: 'internal-review',
    description: 'Updated pitch deck for MFD channel on Tata Mid Cap Opportunities fund',
  },
  {
    id: 'p9',
    clientId: 'c6',
    clientName: 'Invesco MF',
    name: 'ELSS Season — Social Calendar',
    status: 'awaiting-finance',
    budget: 150000,
    spent: 150000,
    dueDate: '2026-06-18',
    deliverableType: 'statics',
    workflowStage: 'closure',
    description: '12-week social media calendar for ELSS tax-saving push',
  },
  {
    id: 'p10',
    clientId: 'c7',
    clientName: 'HDFC AMC',
    name: 'Balanced Advantage — IFA Education Series',
    status: 'on-track',
    budget: 480000,
    spent: 144000,
    dueDate: '2026-08-01',
    deliverableType: 'reels',
    workflowStage: 'research',
    description: '8-part education series for IFA community on Balanced Advantage category dynamics',
  },
  {
    id: 'p11',
    clientId: 'c7',
    clientName: 'HDFC AMC',
    name: 'Annual Report — Creative Direction',
    status: 'on-track',
    budget: 750000,
    spent: 150000,
    dueDate: '2026-08-15',
    deliverableType: 'deck',
    workflowStage: 'clarify-objective',
    description: 'End-to-end creative direction for HDFC AMC annual report FY2025-26',
  },
  {
    id: 'p12',
    clientId: 'c8',
    clientName: 'Nippon MF',
    name: 'SmallCap Fund — Risk Disclosure Campaign',
    status: 'on-track',
    budget: 165000,
    spent: 49500,
    dueDate: '2026-07-20',
    deliverableType: 'statics',
    workflowStage: 'script',
    description: 'Compliance-aligned campaign contextualizing small-cap risk for retail investors',
  },
]

// TODO: replace with GET /api/leads
export const leads: Lead[] = [
  {
    id: 'l1',
    company: 'Franklin Templeton India',
    contactName: 'Rohit Srivastava',
    contactTitle: 'VP Marketing',
    stage: 'negotiation',
    expectedValue: 1200000,
    nextAction: 'Send revised SOW with monthly retainer breakdown',
    nextActionDate: '2026-06-23',
    source: 'Referral — Axis MF',
  },
  {
    id: 'l2',
    company: 'Mirae Asset India',
    contactName: 'Deepika Chandran',
    contactTitle: 'Head of Brand',
    stage: 'proposal-sent',
    expectedValue: 780000,
    nextAction: 'Follow up on Q3 campaign proposal',
    nextActionDate: '2026-06-24',
    source: 'LinkedIn outreach',
  },
  {
    id: 'l3',
    company: 'Edelweiss AMC',
    contactName: 'Farhan Qureshi',
    contactTitle: 'CMO',
    stage: 'meeting-set',
    expectedValue: 540000,
    nextAction: 'Credentials presentation meeting',
    nextActionDate: '2026-06-26',
    source: 'Industry event — AMFI Summit',
  },
  {
    id: 'l4',
    company: 'SBI Mutual Fund',
    contactName: 'Anita Kumari',
    contactTitle: 'DGM Marketing',
    stage: 'contacted',
    expectedValue: 2400000,
    nextAction: 'Share agency capability deck',
    nextActionDate: '2026-06-25',
    source: 'Cold outreach',
  },
  {
    id: 'l5',
    company: 'Zerodha Fund House',
    contactName: 'Nikhil Kamath',
    contactTitle: 'Co-founder',
    stage: 'new',
    expectedValue: 960000,
    nextAction: 'Initial research on brand voice + ICP',
    nextActionDate: '2026-06-28',
    source: 'Inbound — Website',
  },
  {
    id: 'l6',
    company: 'Bandhan AMC',
    contactName: 'Suresh Pillai',
    contactTitle: 'Head of Marketing',
    stage: 'contacted',
    expectedValue: 420000,
    nextAction: 'Send tentative scope for social media retainer',
    nextActionDate: '2026-06-27',
    source: 'Referral — DSP MF',
  },
  {
    id: 'l7',
    company: 'Quant Mutual Fund',
    contactName: 'Prashant Gupta',
    contactTitle: 'Director',
    stage: 'won',
    expectedValue: 600000,
    nextAction: 'Onboarding call scheduled',
    nextActionDate: '2026-06-30',
    source: 'LinkedIn',
  },
  {
    id: 'l8',
    company: 'Groww AMC',
    contactName: 'Siddharth Jain',
    contactTitle: 'VP Growth',
    stage: 'lost',
    expectedValue: 900000,
    nextAction: 'Follow up in 3 months',
    nextActionDate: '2026-09-01',
    source: 'Cold outreach',
  },
]

// TODO: replace with GET /api/revenue
export const revenueData: RevenueDataPoint[] = [
  { month: 'Jul 2025', revenue: 2180000, target: 2200000 },
  { month: 'Aug 2025', revenue: 2450000, target: 2300000 },
  { month: 'Sep 2025', revenue: 2320000, target: 2300000 },
  { month: 'Oct 2025', revenue: 2780000, target: 2500000 },
  { month: 'Nov 2025', revenue: 3100000, target: 2600000 },
  { month: 'Dec 2025', revenue: 3480000, target: 2800000 },
  { month: 'Jan 2026', revenue: 2960000, target: 3000000 },
  { month: 'Feb 2026', revenue: 3220000, target: 3000000 },
  { month: 'Mar 2026', revenue: 3750000, target: 3200000 },
  { month: 'Apr 2026', revenue: 3180000, target: 3200000 },
  { month: 'May 2026', revenue: 3420000, target: 3400000 },
  { month: 'Jun 2026', revenue: 2840000, target: 3500000 },
]

// TODO: replace with GET /api/approvals
export const approvals: ApprovalItem[] = [
  {
    id: 'a1',
    clientName: 'Axis MF',
    projectName: 'Retirement Planning — 10-Part Reel IP',
    itemDescription: 'Retirement Reels Script v2 — Episodes 1–3',
    waitingOn: 'compliance sign-off',
    daysWaiting: 3,
    priority: 'urgent',
  },
  {
    id: 'a2',
    clientName: 'Motilal Oswal',
    projectName: 'MOSt Focused 25 — Brand Film',
    itemDescription: 'Final Cut v1 — Brand Film (3:45 min)',
    waitingOn: 'SEBI compliance review',
    daysWaiting: 8,
    priority: 'urgent',
  },
  {
    id: 'a3',
    clientName: 'DSP MF',
    projectName: 'Tiger Fund — 25 Year Milestone Campaign',
    itemDescription: 'Creative territory presentation (3 routes)',
    waitingOn: 'founder approval before client share',
    daysWaiting: 2,
    priority: 'normal',
  },
  {
    id: 'a4',
    clientName: 'Kotak MF',
    projectName: 'Kotak Flexi Cap — Awareness Reels',
    itemDescription: 'Revised scripts v3 based on client feedback',
    waitingOn: 'internal review',
    daysWaiting: 5,
    priority: 'normal',
  },
  {
    id: 'a5',
    clientName: 'Franklin Templeton',
    projectName: 'New Business',
    itemDescription: 'Revised SOW and pricing (retainer proposal)',
    waitingOn: 'sign-off before sending to client',
    daysWaiting: 1,
    priority: 'urgent',
  },
  {
    id: 'a6',
    clientName: 'Invesco MF',
    projectName: 'ELSS Season — Social Calendar',
    itemDescription: 'Project closure and final invoice release',
    waitingOn: 'finance department approval',
    daysWaiting: 4,
    priority: 'normal',
  },
]

// TODO: replace with GET /api/invoices
export const invoices: Invoice[] = [
  {
    id: 'inv1',
    clientId: 'c1',
    clientName: 'Axis MF',
    amount: 850000,
    dueDate: '2026-06-30',
    issuedDate: '2026-06-01',
    status: 'due',
    daysOverdue: 0,
    invoiceNumber: 'ZW-2026-0112',
    description: 'June Retainer + Reel Production Advance',
  },
  {
    id: 'inv2',
    clientId: 'c1',
    clientName: 'Axis MF',
    amount: 1700000,
    dueDate: '2026-05-31',
    issuedDate: '2026-05-01',
    status: 'overdue',
    daysOverdue: 21,
    invoiceNumber: 'ZW-2026-0098',
    description: 'Q1 Campaign Production — Final Tranche',
  },
  {
    id: 'inv3',
    clientId: 'c2',
    clientName: 'Motilal Oswal',
    amount: 975000,
    dueDate: '2026-06-15',
    issuedDate: '2026-05-15',
    status: 'overdue',
    daysOverdue: 6,
    invoiceNumber: 'ZW-2026-0105',
    description: 'Brand Film Pre-Production + June Retainer',
  },
  {
    id: 'inv4',
    clientId: 'c3',
    clientName: 'Kotak MF',
    amount: 750000,
    dueDate: '2026-05-20',
    issuedDate: '2026-04-20',
    status: 'overdue',
    daysOverdue: 32,
    invoiceNumber: 'ZW-2026-0089',
    description: 'Flexi Cap Reel Campaign — Milestone 2',
  },
  {
    id: 'inv5',
    clientId: 'c3',
    clientName: 'Kotak MF',
    amount: 750000,
    dueDate: '2026-06-20',
    issuedDate: '2026-05-20',
    status: 'overdue',
    daysOverdue: 1,
    invoiceNumber: 'ZW-2026-0101',
    description: 'Flexi Cap Reel Campaign — Milestone 3',
  },
  {
    id: 'inv6',
    clientId: 'c4',
    clientName: 'DSP MF',
    amount: 630000,
    dueDate: '2026-07-01',
    issuedDate: '2026-06-01',
    status: 'due',
    daysOverdue: 0,
    invoiceNumber: 'ZW-2026-0110',
    description: 'Tiger Fund Campaign — Advance',
  },
  {
    id: 'inv7',
    clientId: 'c6',
    clientName: 'Invesco MF',
    amount: 840000,
    dueDate: '2026-04-30',
    issuedDate: '2026-03-31',
    status: 'overdue',
    daysOverdue: 52,
    invoiceNumber: 'ZW-2026-0071',
    description: 'ELSS Season Campaign — Final Settlement',
  },
  {
    id: 'inv8',
    clientId: 'c7',
    clientName: 'HDFC AMC',
    amount: 920000,
    dueDate: '2026-07-15',
    issuedDate: '2026-06-15',
    status: 'due',
    daysOverdue: 0,
    invoiceNumber: 'ZW-2026-0115',
    description: 'IFA Education Series — Phase 1 + Retainer',
  },
]

// TODO: replace with GET /api/opportunity-alerts
export const opportunityAlerts: OpportunityAlert[] = [
  {
    id: 'oa1',
    clientName: 'Motilal Oswal',
    signal: '3 social posts from last campaign received above-average organic reach (+240%) — no paid boost, pure content quality. No performance retainer in place yet.',
    suggestedAction: 'Propose performance amplification retainer (₹2L/month)',
    potentialValue: 2400000,
    urgency: 'high',
  },
  {
    id: 'oa2',
    clientName: 'HDFC AMC',
    signal: 'Annual report brief scope has expanded — legal and compliance want a 48-page version, up from 24. No change order raised.',
    suggestedAction: 'Raise change order for scope expansion before milestone 2',
    potentialValue: 350000,
    urgency: 'high',
  },
  {
    id: 'oa3',
    clientName: 'DSP MF',
    signal: '25th anniversary campaign goes live in Q3. No PR/media amplification brief received yet — likely an oversight.',
    suggestedAction: 'Pitch integrated PR + media amplification module',
    potentialValue: 800000,
    urgency: 'medium',
  },
  {
    id: 'oa4',
    clientName: 'Tata MF',
    signal: 'New NFO expected in August (Tata Business Cycle Fund). Historical pattern: NFO campaigns are always rushed with no pre-planning.',
    suggestedAction: 'Initiate NFO campaign planning conversation now — 6-week lead time needed',
    potentialValue: 450000,
    urgency: 'medium',
  },
]

// TODO: replace with GET /api/projects/axis-retirement-reel
export const axisProjectData: AxisProject = {
  id: 'p1',
  clientId: 'c1',
  clientName: 'Axis MF',
  name: 'Retirement Planning — 10-Part Reel IP',
  status: 'on-track',
  budget: 450000,
  spent: 210000,
  dueDate: '2026-07-15',
  deliverableType: 'reels',
  workflowStage: 'script',
  currentStageIndex: 4,
  description: '10-episode educational reel series on retirement corpus building for the 35–50 age segment',
  briefSummary:
    'Axis MF wants to create a differentiated content IP around retirement planning — an underserved topic in AMC content. The brief asks for "educational reels" but the real ask is establishing Axis MF as the category authority for retirement corpus building among the 35–50 age cohort. The 10-part structure is open to creative reinterpretation.',
  campaignArchitect: {
    decodedAsk:
      "Axis MF's brief says '10 educational reels about retirement planning.' The actual ask is deeper: they want to own the 'retirement corpus' conversation among working professionals aged 35–50 who are 15–20 years from retirement but haven't started planning seriously. The reels are the vehicle; category authority is the destination. The 10-episode format is a structural suggestion, not a constraint — if 7 episodes land harder, that's the better answer.",
    objectiveHypothesis:
      "Success looks like this: a 40-year-old financial professional watches Episode 1, shares it to their WhatsApp group with the caption 'this is exactly what I needed,' and is back for Episode 3 without prompting. The content must generate personal resonance, not just awareness. Secondary objective: IFAs use these reels as client education tools — which means the content must also be credible to advisors who review it critically. Tertiary: shareable enough to generate organic reach without paid amplification.",
    fixedConstraints: [
      'SEBI advertising guidelines for mutual funds — no projected returns, no specific fund performance claims',
      'Axis MF brand voice: authoritative but not intimidating, warm but not casual',
      'Each reel must include regulatory disclaimer (15-second voice-over tag at end)',
      'No competitor fund mentions or indirect comparisons',
      'Content must be approved by Axis MF compliance before production',
      'Mobile-first vertical format (9:16) — designed for Instagram Reels and YouTube Shorts',
    ],
    flexibleAreas: [
      'Episode structure — not locked to 10 parts if a different number serves the narrative arc better',
      'Talent choice — the brief didn\'t specify whether to use a known face, the client\'s own spokesperson, or anonymized characters',
      'Tonal range — brief says "educational" but we have latitude to go narrative/documentary/dramatized if it earns more attention',
      'Episode length — 60s, 90s, or 2-minute formats are all viable; recommend testing with 2–3 episode lengths',
      'Visual language — no brand style guide constraint beyond logo and color usage',
      'Call-to-action mechanism — brief is silent on where to direct viewers after watching',
    ],
    missingQuestions: [
      "What's the primary distribution channel — Axis MF's own handles, paid social, IFA network sharing, or all three? The answer changes the content design significantly.",
      "Is there a specific sub-segment within 35–50? (E.g., salaried vs. self-employed, tier-1 vs. tier-2 cities, HNI vs. mass affluent?) Each requires a different emotional entry point.",
      "Does Axis MF have existing research or proprietary data on retirement readiness that could anchor the series? Proprietary data = instant credibility hook.",
      "What's the compliance turnaround time? We're budgeting 7 days — if it's longer, the production schedule collapses.",
      "Is there a specific fund or product to soft-seed within the series, or is this a pure category/brand play?",
    ],
    recommendedWorkflow:
      'Given the compliance constraints and the 10-episode scale, we recommend a phased production approach: (1) Finalize 3 script templates across different tonal registers and send all three for compliance review simultaneously — not sequentially. (2) Green-light the highest-clearing template and produce Episodes 1–3 as a pilot batch. (3) Use pilot performance data (reach, shares, saves) to calibrate Episodes 4–10. This approach protects us against a full compliance rejection killing the entire series. Budget reserve of ₹45K (10%) held for potential reshoots.',
    creativeTerritoriesIntro:
      'Three distinct creative territories were explored — each hits the same strategic objective from a different emotional angle. Recommendation is Territory A, with Territory B as a strong fallback depending on the talent decision.',
    creativeTerritories: [
      {
        name: 'Territory A: "The Math Nobody Showed You"',
        premise:
          'A series that uses surprising, counterintuitive numbers to reframe how 35–50 year olds think about retirement. Each episode opens with a number that shocks — then explains it. The tone is that of a sharp friend who happens to know everything about money, not a financial advisor.',
        exampleTreatment:
          'Episode 1 opens with: "₹4.2 crore. That\'s what you need to retire comfortably in Delhi in 2040. You have 15 years. Right now, you have ₹12 lakh saved." Cut to a relatable visual — morning commute, kid\'s school drop-off. Voice-over: "This isn\'t to scare you. It\'s to help you do the math your job never taught you." The rest of the reel breaks down the compound growth math in 60 seconds. End frame: "This series exists because retirement planning is too important to keep being boring."',
        tonalQuality: 'Confident, clear-eyed, slightly provocative — earns trust by respecting the viewer\'s intelligence',
      },
      {
        name: 'Territory B: "Stories from 2045"',
        premise:
          'A narrative docuseries format — short fictional vignettes of two contrasting characters at retirement age: one who planned early, one who didn\'t. Not preachy. Cinematic. The contrast does the work without moralizing. Each episode flashes back to the decision (or non-decision) made at age 40.',
        exampleTreatment:
          'Episode 1: A 62-year-old Meenakshi in a sunlit apartment, unhurried, choosing her own breakfast. A 62-year-old Rajesh in his brother-in-law\'s spare bedroom. No commentary. Flash back to 2026: Meenakshi sets up a ₹10K SIP on her phone during lunch break. Rajesh dismisses it as "I\'ll deal with this next year." End card: "Your 2026 decisions live in your 2045." Understated. Powerful.',
        tonalQuality: 'Cinematic, emotionally resonant, aspirational without being aspirational',
      },
      {
        name: 'Territory C: "Ask the Right Question"',
        premise:
          'Each episode opens with the wrong question most people ask about retirement — then reframes it into the question that actually matters. Format works as a Q&A but with a twist: the question itself is the insight. Works well with a presenter format.',
        exampleTreatment:
          'Episode 1: "Wrong question: How much should I save for retirement? Right question: What does your retirement actually cost?" The reel then walks through building a real retirement budget — not abstract percentages, but actual expense line items. Fun, fast-paced, reference-able. Very shareable.',
        tonalQuality: 'Smart-casual, accessible, designed for IFA sharing to client WhatsApp groups',
      },
    ],
  },
  deliverables: [
    { id: 'd1', name: 'AxisMF_Retirement_Brief_Decoded_v1.pdf', type: 'deck', version: 1, status: 'approved', lastUpdated: '2026-06-05', updatedBy: 'Priya Mehta' },
    { id: 'd2', name: 'AxisMF_Retirement_CreativeTerritory_v2.pdf', type: 'deck', version: 2, status: 'approved', lastUpdated: '2026-06-10', updatedBy: 'Rahul Sharma' },
    { id: 'd3', name: 'AxisMF_Retirement_Script_Ep1-3_v1.docx', type: 'script', version: 1, status: 'needs-revision', lastUpdated: '2026-06-14', updatedBy: 'Aparna Krishnan' },
    { id: 'd4', name: 'AxisMF_Retirement_Script_Ep1-3_v2.docx', type: 'script', version: 2, status: 'in-review', lastUpdated: '2026-06-19', updatedBy: 'Aparna Krishnan' },
    { id: 'd5', name: 'AxisMF_Retirement_Storyboard_Ep1_v1.pdf', type: 'storyboard', version: 1, status: 'draft', lastUpdated: '2026-06-20', updatedBy: 'Vikram Patel' },
    { id: 'd6', name: 'AxisMF_Retirement_Script_Ep4-6_v1.docx', type: 'script', version: 1, status: 'draft', lastUpdated: '2026-06-21', updatedBy: 'Aparna Krishnan' },
    { id: 'd7', name: 'AxisMF_BrandGuidelines_Reference.pdf', type: 'deck', version: 1, status: 'approved', lastUpdated: '2026-05-28', updatedBy: 'Priya Mehta' },
    { id: 'd8', name: 'AxisMF_Retirement_ComplianceChecklist_v1.docx', type: 'deck', version: 1, status: 'in-review', lastUpdated: '2026-06-18', updatedBy: 'Legal Team' },
  ],
  activityLog: [
    { id: 'al1', actorName: 'Priya Mehta', actorInitials: 'PM', actorColor: '#c9a85c', action: 'uploaded revised scripts for Episodes 1–3', target: 'AxisMF_Retirement_Script_Ep1-3_v2.docx', timestamp: '2026-06-19T14:32:00', type: 'upload' },
    { id: 'al2', actorName: 'Vivek Arora (Axis MF)', actorInitials: 'VA', actorColor: '#5b8dee', action: 'left feedback on compliance language in Episode 2', target: 'Script v1', timestamp: '2026-06-18T11:15:00', type: 'feedback' },
    { id: 'al3', actorName: 'Aparna Krishnan', actorInitials: 'AK', actorColor: '#4caf7d', action: 'moved project to Script stage', target: 'Workflow', timestamp: '2026-06-17T09:00:00', type: 'stage-change' },
    { id: 'al4', actorName: 'Rahul Sharma', actorInitials: 'RS', actorColor: '#e89a3c', action: 'submitted Creative Territory v2 for client review', target: 'AxisMF_Retirement_CreativeTerritory_v2.pdf', timestamp: '2026-06-10T16:45:00', type: 'approval' },
    { id: 'al5', actorName: 'Vivek Arora (Axis MF)', actorInitials: 'VA', actorColor: '#5b8dee', action: 'approved Creative Territory A — "The Math Nobody Showed You"', target: 'Creative Territory', timestamp: '2026-06-12T10:20:00', type: 'approval' },
    { id: 'al6', actorName: 'Priya Mehta', actorInitials: 'PM', actorColor: '#c9a85c', action: 'scheduled kick-off call with Axis MF brand team', target: 'Project', timestamp: '2026-06-03T13:00:00', type: 'comment' },
    { id: 'al7', actorName: 'Aparna Krishnan', actorInitials: 'AK', actorColor: '#4caf7d', action: 'completed category scan for BFSI retirement content landscape', target: 'Research doc', timestamp: '2026-06-07T15:30:00', type: 'upload' },
    { id: 'al8', actorName: 'Vikram Patel', actorInitials: 'VP', actorColor: '#c9a85c', action: 'started storyboard for Episode 1', target: 'AxisMF_Retirement_Storyboard_Ep1_v1.pdf', timestamp: '2026-06-20T11:00:00', type: 'upload' },
    { id: 'al9', actorName: 'Rahul Sharma', actorInitials: 'RS', actorColor: '#e89a3c', action: 'flagged disclaimer language issue in Episode 2 script — needs legal review', target: 'Script v2 — Episode 2', timestamp: '2026-06-19T17:00:00', type: 'comment' },
    { id: 'al10', actorName: 'Priya Mehta', actorInitials: 'PM', actorColor: '#c9a85c', action: 'raised compliance review request with legal team', target: 'AxisMF_Retirement_ComplianceChecklist_v1.docx', timestamp: '2026-06-18T09:30:00', type: 'review' },
    { id: 'al11', actorName: 'Aparna Krishnan', actorInitials: 'AK', actorColor: '#4caf7d', action: 'began drafting scripts for Episodes 4–6', target: 'AxisMF_Retirement_Script_Ep4-6_v1.docx', timestamp: '2026-06-21T10:00:00', type: 'upload' },
  ],
}
